Models/Leave.cs
namespace ELMSApplication;
using System.ComponentModel.DataAnnotations;

public class Leave
{
    [Key]
    public int LeaveId { get; set; }
    public string? EmployeeId { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    [StringLength(75)]
    public string? LeaveType { get; set; }
    [StringLength(75)]
    public string? Status { get; set; }

}

Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ELMSApplication;

namespace ELMSApplication.Controllers
{
    public class LeaveController : Controller
    {
        private readonly ELMSApplicationContext _context;
       
        public LeaveController(ELMSApplicationContext context)
        {
            _context = context;
        }

        // GET: Leave
        public async Task<IActionResult> Index()
        {

           // string? employeeId = TempData["EmployeeID"] as string;
           // string? admin = TempData["Admin"] as string;
             string? employeeId =  HttpContext.Session.GetString("EmployeeID");
            string? admin = HttpContext.Session.GetString("Admin");
             var leave = from l in _context.Leave
                   select l;
            if(_context.Leave != null)
            {
                if(admin.Equals("False"))
                {                   
                       leave = leave.Where(l => l.EmployeeId.Equals(employeeId));
                }
                
            }
            else{
                    Problem("Entity set 'ELMSApplicationContext.Leave'  is null.");
            }
            //TempData.Keep("Admin");
           
           // TempData.Keep("EmployeeName");
            //TempData.Keep("EmployeeID");            
            return View(await leave.AsNoTracking().ToListAsync());        
                          
        }

        // GET: Leave/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Leave == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave
                .FirstOrDefaultAsync(m => m.LeaveId == id);
            if (leave == null)
            {
                return NotFound();
            }
            //TempData.Keep("Admin");
            //TempData.Keep("EmployeeName");
            //TempData.Keep("EmployeeID");  
            return View(leave);
        }

        // GET: Leave/Create
        public IActionResult Create()
        {
            //TempData.Keep("Admin");
            //TempData.Keep("EmployeeName");
            //TempData.Keep("EmployeeID");  
            return View();
        }

        // POST: Leave/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LeaveId,EmployeeId,StartDate,EndDate,LeaveType,Status")] Leave leave)
        {
            if (ModelState.IsValid)
            {
                try{
                    _context.Add(leave);
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex){ throw;}                 
                return RedirectToAction(nameof(Index));
            }       
            //TempData.Keep("Admin");    
            return View(leave);
        }

        // GET: Leave/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Leave == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave.FindAsync(id);
            if (leave == null)
            {
                return NotFound();
            }
            return View(leave);
        }

        // POST: Leave/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveId,EmployeeId,StartDate,EndDate,LeaveType,Status")] Leave leave)
        {
            if (id != leave.LeaveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveExists(leave.LeaveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           // TempData.Keep("Admin");
         //   TempData.Keep("EmployeeName");
           // TempData.Keep("EmployeeID");  
            return View(leave);
        }

        // GET: Leave/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Leave == null)
            {
                return NotFound();
            }

            var leave = await _context.Leave
                .FirstOrDefaultAsync(m => m.LeaveId == id);
            if (leave == null)
            {
                return NotFound();
            }            

            return View(leave);
        }

        // POST: Leave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Leave == null)
            {
                return Problem("Entity set 'ELMSApplicationContext.Leave'  is null.");
            }
            var leave = await _context.Leave.FindAsync(id);
            if (leave != null)
            {
                _context.Leave.Remove(leave);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

         public async Task<IActionResult> ApprovedAsync(int id)
         {
            var leave = await _context.Leave.FindAsync(id);
            leave.Status ="Approved";
            _context.Update(leave);
                    await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
         } 

         public async Task<IActionResult> RejectedAsync(int id)
         {
            var leave = await _context.Leave.FindAsync(id);
            leave.Status ="Rejected";
            _context.Update(leave);
                    await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
         } 

        private bool LeaveExists(int id)
        {
          return (_context.Leave?.Any(e => e.LeaveId == id)).GetValueOrDefault();
        }
    }
}

Views/Leave/Approved.cshtml
@model ELMSApplication.Leave

@{
    ViewData["Title"] = "Approved";
}

Views/Leave/Create.cshtml
@model ELMSApplication.Leave

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Leave</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <input asp-for="EmployeeId" class="form-control" />
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveType" class="control-label"></label>
                <input asp-for="LeaveType" class="form-control" />
                <span asp-validation-for="LeaveType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Leave/Delete.cshtml
@model ELMSApplication.Leave

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LeaveId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Leave/Details.cshtml
@model ELMSApplication.Leave

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Leave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @if (@Context.Session.GetString("Admin") != null && @Context.Session.GetString("Admin").Equals("False"))
 {
    <a asp-action="Edit" asp-route-id="@Model?.LeaveId">Edit</a> } |
    <a asp-action="Index">Back to List</a>
</div>

Views/Leave/Edit.cshtml
@model ELMSApplication.Leave

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Leave</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LeaveId" />
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <input asp-for="EmployeeId" class="form-control" />
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveType" class="control-label"></label>
                <input asp-for="LeaveType" class="form-control" />
                <span asp-validation-for="LeaveType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Leave/Index.cshtml
@model IEnumerable<ELMSApplication.Leave>
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc;

@{
    ViewData["Title"] = "Index";
}
<style>
    .gradient-custom-2 {
/* fallback for old browsers */
background-color: rgb(212, 124, 15);

/* Chrome 10-25, Safari 5.1-6 */
/background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);

/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
/background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
}
.gradient-custom-2 {
border-top-right-radius: .3rem;
border-bottom-right-radius: .3rem;
}
    </style>

<h4>Welcome @Context.Session.GetString("EmployeeName")</h4> 

<h1 align="center">Leave Dashboard</h1>
<br></br>
 @if (@Context.Session.GetString("Admin") != null && @Context.Session.GetString("Admin").Equals("False"))
 {
<p>    
     <input type="button"
         value="Create" class="btn btn-success"
         
         onclick="location.href='@Url.Action("Create", "Leave")'"/>
</p>
 }
else
{
<p align="right"><b>To give employee access to the system <a href="http://localhost:5158/swagger/index.html"  class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3 target="_blank">Click here</a></b></p>
}
<br><br/>
<table class="table table-bordered">
      <thead class="thead-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
              <td>
                <input type="button" value="View" class="btn btn-secondary" onclick="location.href='@Url.Action("Details", "Leave",new { id = item.LeaveId})'"  />    
                @if (@Context.Session.GetString("Admin") != null && @Context.Session.GetString("Admin").Equals("True")){ 
                <input type="button" value="Approved" class="btn btn-success" onclick="location.href='@Url.Action("Approved", "Leave",new { id = item.LeaveId})'"  />    
                 <input type="button" value="Rejected" class="btn btn-danger" onclick="location.href='@Url.Action("Rejected", "Leave",new { id = item.LeaveId})'"  />      
                }   
               else
                {
                    <input type="button" value="Edit" class="btn btn-info" onclick="location.href='@Url.Action("Edit", "Leave", new { id = item.LeaveId})'"  />
                    <input type="button" value="Delete" class="btn btn-danger"  onclick="location.href='@Url.Action("Delete", "Leave",new { id = item.LeaveId})'" />
                }  
                  
            </td>
        </tr>
}
    </tbody>
</table>

Views/Leave/Rejected.cshtml
@model ELMSApplication.Leave

@{
    ViewData["Title"] = "Rejected";
}